languages:
  JavaScript: true
 
exclude_paths:
 - "dev/*"
 - "prod/*"
 - "build/npm-debug.log"
 - "build/node_modules/*"
 - "build/files/data/compiled.json"
 - "build/files/img/*"
 - "build/vendor/*"
 - "foo/bar.rb"